### ISSUE TITLE
Add Subtract Method

### ISSUE THREAD

**Issue by mqueirozcorreia** [marsop/ephemeral#13]
It would be nice to have a Subtract one interval, based in another. If you let me do it, I can make a pull request.

I have a interval [8 12] and want to subtract the interval [9 10], the result should be the two intervals [8 9] and [10 12]

**Comment by marsop** [comment]
@mqueirozcorreia thank you for your interest in the project. I would be glad to take a look at your pull request when ready. Let me know if you have any questions.

**Comment by mqueirozcorreia** [comment]
What do you think about this PR?
https://github.com/marsop/ephemeral/pull/14

**Comment by marsop** [comment]
Merged, thanks for the contribution.
