### ISSUE TITLE
Intersect problem

### ISSUE THREAD

**Issue by mqueirozcorreia** [marsop/ephemeral#16]
When using a different combination of start/end included there is an error on Intersect method. Created a Unit Test to show the problem and solved at this PR https://github.com/marsop/ephemeral/pull/15

**Comment by marsop** [comment]
Hi @mqueirozcorreia, once again, thank you for helping with ephemeral. 

I have reviewed the problem and there is indeed a bug, however the solution should be as easy as changing:

var startIncluded = first.Covers(maxStart) && second.Covers(**minEnd**);
var endIncluded = first.Covers(minEnd) && second.Covers(minEnd);

with:

var startIncluded = first.Covers(maxStart) && second.Covers(**maxStart**);
var endIncluded = first.Covers(minEnd) && second.Covers(minEnd);

After this the tests you have prepared are running as expected.

**Comment by mqueirozcorreia** [comment]
Thanks for the review, the code is much nicer in this way. I have updated the PR, can you check?

**Comment by marsop** [comment]
Merged ;-)
