### ISSUE TITLE
Subtract tests and Fix

### ISSUE THREAD

**Issue by mqueirozcorreia** [marsop/ephemeral#18]
I have found some bugs and fixed them on Subtract Implementation on https://github.com/marsop/ephemeral/pull/17
Adding test when starts/ends at the same time and has different start/end included
Fixing bugs discovered with those tests

**Comment by marsop** [comment]
Merged. Please note that Subtract should probably use the special interface defined for this in Ephemeral called: `IDisjointIntervalSet`.

The idea of a disjoint interval set is that we can be sure that the intervals included inside do not overlap. In the end it can be used as a normal IList<IInterval>, with the difference that the intervals inside are chronologically ordered.

**Comment by mqueirozcorreia** [comment]
I can make this change to use the special interface, makes total sense.
