### ISSUE TITLE
Use DisjointIntervalSet as return value for Subtract()

### ISSUE THREAD

**Issue by marsop** [marsop/ephemeral#19]
At the moment we are returning List<Interval> which is sub-optimal since we have an interface to define the shape of the returning object.

**Comment by mqueirozcorreia** [comment]
Just did here https://github.com/marsop/ephemeral/pull/20

Please let me know if you miss any other thing.

**Comment by marsop** [comment]
Merged. 

Thanks a lot @mqueirozcorreia
