### ISSUE TITLE
Create a set of tests demonstrating the capabilities of each method

### ISSUE THREAD

**Issue by marsop** [marsop/ephemeral#3]

**Comment by jordihereu** [comment]
Hey @marsop I can give a hand

**Comment by marsop** [comment]
> Hey @marsop I can give a hand

That would be awesome 😄 

Do you need some help understanding the methods? I can provide an overview if that would be helpful.

**Comment by jordihereu** [comment]
I created a test project and a test class with some tests for IntervalStartComparer , which is the easiest. I'll do the PR later today (or tomorrow), so we can discuss if the project structure and the guidelines are ok for you.
Then we can check the other methods in a different PR maybe.
