### ISSUE TITLE
Create the documentation of the API

### ISSUE THREAD

**Issue by marsop** [marsop/ephemeral#4]

**Comment by SabhaKandula** [comment]
Hello 
I would like to contribute to this project. This could be my first open-source contribution. Can you please guide me through?

**Comment by marsop** [comment]
Hi @SabhaKandula. Glad to hear that you want to collaborate with an OSS project. The idea for this issue is to create a documentation (either automatically generated from code or directly writing it as markdown). 

You can start by forking the project in your own GitHub account and cloning the code locally using a git client. After that try to build it locally and observe the methods already defined in `IInterval`. You can start by trying to document those:

- Inputs: what does this method require?
- Outputs: what will be returned?
- (optionally): Notes or gotchas about the method.

If you have any doubt please contact me, I will be glad to help in the process.

**Comment by SabhaKandula** [comment]
Do you want me to write code comments or contribute to readme file?

**Comment by marsop** [comment]
I think the way to go would be something like https://dotnet.github.io/docfx/index.html or similar (Doxygen, ReadTheDocs)

**Comment by Defkon1** [comment]
If SabhaKandula has changed his mind I can do it...

Have you ever thought about enforcing StyleCop rules on your code?



EDIT/ fixed typo

**Comment by marsop** [comment]
@Defkon1 would you be interested in adding StyleCop and improving the code based on its recommendations? that will also be greatly appreciated.

**Comment by Defkon1** [comment]
here you are: https://github.com/marsop/ephemeral/pull/8

there are a couple of design problems in your classes,too... if you want I can prepare a separate PR, so you can evaluate by yourself if merge it or not...

**Comment by marsop** [comment]
Merged, would you mind to comment the perceived problems in the classes in a separate issue?

**Comment by Defkon1** [comment]
the main problem is the missing of checks on null parameters in methods, and you are often relying on the parent classes to manage exceptions.

in a couple of cases  there is some redundant code (e.g. inside the IntervalStartComparer)

**Comment by Defkon1** [comment]
Sorry, English is not my first language and maybe my last comment sounded more arrogant than I wanted.

I'd like to use your library as a basis for a small project to be carried out by some interns of my company in the next weeks, and I'd like to clean out a couple of things before they start.

If it's not a problem for you I will go on with code reviews and refactors on my fork, and I will send to you PRs of the main edits; feel free to discard any pull request you find inappropriate for the direction you want to give to your project.

Have a great day!

**Comment by marsop** [comment]
No problem at all. I am truly glad that you would like to use the project 😄 

Please feel free to send PR, I will try to review them as soon as possible. 

Regarding null parameters: the idea is to jump into .NET Core 3 and (non-)NullableReferenceTypes as soon as possible. This would mean that we take it for granted that the parameters to methods should not be null. However, and following Microsoft guidelines, the APIs should not assume this is the case until the next release, therefore I think it is not a bad idea to check the parameters against null everywhere in the meantime.

Maybe also of use for you, there is a first version of this package in nuget (Marsop.Ephemeral). Once the null checks are in place I will create a new version in nuget. Maybe you could use that one for your interns.

**Comment by marsop** [comment]
Documentation is now available under https://albertogregorio.com/ephemeral
